import { envList } from '../envList.js';
import { test3 } from './test3.js';
import { add } from './test2.js';
export const a = add;
export const b = '22';
export const c = '22';
export const d = '22';
export const e = '22';
export const f = '22';
export const g = '22';
console.log(test3);
console.log(envList);
console.log('helloworld-12333');
